In [2]:
import numpy as np
x = np.array([2,5,6])

In [6]:
print(x)
print(x.shape)

y = np.array([
    [1,2,3],
    [4,5,6]
])
print(y)
print(y.shape)

[2 5 6]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [8]:
z = np.arange(1,10,.2)
print(z)
print(z.shape)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
(45,)


In [9]:
a = np.linspace(1,10,20)
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [12]:
print(z.reshape(9,5))
print(z.reshape(3,3,5))

[[1.  1.2 1.4 1.6 1.8]
 [2.  2.2 2.4 2.6 2.8]
 [3.  3.2 3.4 3.6 3.8]
 [4.  4.2 4.4 4.6 4.8]
 [5.  5.2 5.4 5.6 5.8]
 [6.  6.2 6.4 6.6 6.8]
 [7.  7.2 7.4 7.6 7.8]
 [8.  8.2 8.4 8.6 8.8]
 [9.  9.2 9.4 9.6 9.8]]
[[[1.  1.2 1.4 1.6 1.8]
  [2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]
  [6.  6.2 6.4 6.6 6.8]]

 [[7.  7.2 7.4 7.6 7.8]
  [8.  8.2 8.4 8.6 8.8]
  [9.  9.2 9.4 9.6 9.8]]]


In [15]:
np.random.randint(1,1000,(3,3))

array([[331, 548, 445],
       [217, 548,  34],
       [949, 101, 579]])

In [23]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([
    [4,2,3],
    [4,8,6]
])
print(f'{a+b}\n')
print(a*b)
print(a/b)
print(a%b)
print(a**b)
print(a-b)


[[ 5  4  6]
 [ 8 13 12]]

[[ 4  4  9]
 [16 40 36]]
[[0.25  1.    1.   ]
 [1.    0.625 1.   ]]
[[1 0 0]
 [0 5 0]]
[[     1      4     27]
 [   256 390625  46656]]
[[-3  0  0]
 [ 0 -3  0]]


In [26]:
print(a.dot(b.T))
print(a @ b.T)
print(np.matmul(a,b.T))

[[17 38]
 [44 92]]
[[17 38]
 [44 92]]
[[17 38]
 [44 92]]


In [31]:
print(a.sum()) # sum of all element
print(a.sum(axis=0)) #sum of columns
print(a.sum(axis=1)) #sum of rows
print(a.mean())
print(a.min())
print(a.max())
print(a.std()) #standard daviation
print(a.argmax()) #index of maximum element
print(a.argmin()) #index of minimum element

21
[5 7 9]
[ 6 15]
3.5
1
6
1.707825127659933
5
0


In [34]:
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.arcsin(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
[[1.57079633        nan        nan]
 [       nan        nan        nan]]


C:\Users\Farhan\AppData\Local\Temp\ipykernel_1968\3713717503.py:4: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(a))


In [36]:
print(a[0,:])
print(a[:,0])
print(a[0,0])
print(a[:2,:2])
print(a[:2])


[1 2 3]
[1 4]
1
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]
